---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'git@github.com:kenbunitag/placid-eks-argocd-test.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      selfHeal: true
