apiVersion: v1
kind: Secret
metadata:
  name: placid-eks-argocd-test
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/kenbunitag/placid-eks-argocd-test.git
  sshPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
  ...
  ...
    -----END RSA PRIVATE KEY-----
  insecure: "false" # Do not perform a host key check for the server. Defaults to "false"
  enableLfs: "false" # Enable git-lfs for this repository. Defaults to "false"
